### ISSUE TITLE
Provide examples of compression

### ISSUE THREAD

**Issue by bradleyayers** [xylk/prosemirror-compress#1]
Really interesting library idea!

It would be useful to provide examples of the compression output, so that readers can make a quick assessment for how appropriate this library is for their use-case.

**Comment by xylk** [comment]
Thanks! Just added [an example](https://github.com/xylk/prosemirror-compress#uncompressed-vs-compressed). Would you prefer more details?

**Comment by bradleyayers** [comment]
Ah that's very helpful thanks! So it's basically just predefined key-elision, neat.
