### ISSUE TITLE
Support value-based keymaps

### ISSUE THREAD

**Issue by bradleyayers** [xylk/prosemirror-compress#2]
It would be useful to support value-based keymaps, so that node types like `doc` or `paragraph` and mark types like `strong` could be elided to just `doc`, `p`,r `s`. The same would be useful for arbitrary attribute values.

For example I have a mark `subsup` (which is short for `superscript/subscript`. It has a `type` attribute with the value `sub` or `sup` (to indicate whether the mark represents subscript or superscript). It would be handy to be able to have key elision apply to these too.

**Comment by xylk** [comment]
Supported with https://github.com/xylk/prosemirror-compress/commit/c453036517bb6a068231d5844d5e173f4b7c6759.
